services:
  app:
    build:
      dockerfile: ./services/php/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_TAGS: dev
    working_dir: /var/www/application
    volumes:
      - ./application:/var/www/application
      - ./services/php/config/local.ini:/usr/local/etc/php/conf.d/local.ini
    hostname: app
    networks:
      - app-network
  app_debug:
    build:
      context: ./services/php/debug
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app_debug
      SERVICE_TAGS: dev
    working_dir: /var/www/application
    volumes:
      - ./application:/var/www/application
      - ./services/php/config/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./services/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    hostname: app_debug
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./application:/var/www/application
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
  db:
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    hostname: db
    networks:
      - app-network
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    hostname: redis
    networks:
      - app-network
volumes:
  mysql_data:
  redis_data:
networks:
  app-network:
    driver: bridge
