version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./services/php/Dockerfile
    image: php:8.1
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./application:/var/www/application
      - ./services/php/config/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application:/var/www/application
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    hostname: db
    networks:
      - app-network
volumes:
  mysql_data:
networks:
  app-network:
    driver: bridge